### PR TITLE
Fixed: Download Svg Button

### LINKED ISSUE #15: Option to export to pdf/jpg/...
First thanks for this really nice tool (the only open source one I can find on the whole internet so far...). But it still lacks a feature I'd really love to have: the ability to export the drawing into another format (png for example). It would be great to be able to save a document.

Thanks!

### PR DESCRIPTION
**Pull request by DanielHabenicht**
Hi, 

this PR addresses the requested changes on #122. Mainly: 
- does not make any changes to the `svg` area but rather clones it and then modifies it.
- fixes the icon so if fits with the others 
- fixes reported styling issues
- now uses the board name as filename

image

fixes #15 

Hit me up if something else is missing or not working. 

<sub>
By opening a pull request, I certify that I hold the intellectual property of the code I am submitting,
and I am granting the initial authors of WBO a perpetual, worldwide, non-exclusive, royalty-free, and irrevocable license to this code.
</sub>

### CODE REVIEW

File: client-data/tools/download/download.js [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+ *
+ * @licend
+ */
+
+(function download() { //Code isolation
+
+    function downloadSVGFile(evt) {
+        var canvasCopy = document.getElementById('canvas').cloneNode(true);
+        var styleNode = document.createElement("style");
+        styleNode.innerHTML = "rect, ellipse { fill:none; } path, line {fill: none;stroke-linecap: round; stroke-linejoin: round;}";
```
Comment (lovasoa) [inline client-data/tools/download/download.js:32]: Isn't there a way to get the actual style used on the page ? 
Putting it there means that any change or addition has to happen here AND in the respective CSS files of the different tools.

File: client-data/tools/download/download.js [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+ * section 4, provided you include this license notice and a URL
+ * through which recipients can access the Corresponding Source.
+ *
+ * @licend
+ */
+
+(function download() { //Code isolation
+
+    function downloadSVGFile(evt) {
+        var canvasCopy = document.getElementById('canvas').cloneNode(true);
```
Comment (lovasoa) [inline client-data/tools/download/download.js:30]: You should get the canvas from the `Tools.svg` element.

File: client-data/tools/download/download.js (hunk 1 above)
Comment (DanielHabenicht) [reply client-data/tools/download/download.js]: In the PR of @sents `document.stylesheets` is used. 
https://github.com/sents/whitebophir/blob/fea42297dfbf5e219be87989505f5d0c441d9680/client-data/js/board.js#L613-L620

I added it and named him as Co-Author

File: client-data/tools/download/download.js (hunk 2 above)
Comment (DanielHabenicht) [reply client-data/tools/download/download.js]: done

File: client-data/tools/download/download.js (hunk 1 above)
Comment (DanielHabenicht) [reply client-data/tools/download/download.js]: another way would be to add svg specific styles to the SVG, because now we are also copying website css to the exported SVG.

**Comment by DanielHabenicht** [comment]
One more thing: Would you be interested in PNG Export as well (in another PR)? 
I would need to add a package for that https://github.com/canvg/canvg

File: client-data/tools/download/download.js [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+(function download() { //Code isolation
+
+    function downloadSVGFile(evt) {
+        var canvasCopy = Tools.svg.cloneNode(true);
+        var styleNode = document.createElement("style");
+
+        // Copy the stylesheets from the whiteboard to the exported SVG
+        stylesheets = document.styleSheets;
+        styleText = "";
+        Array.from(stylesheets).forEach(stylesheet => {
```
Comment (lovasoa) [inline client-data/tools/download/download.js:36]: We support older browsers without array functions

**Comment by sents** [comment]
Actually just using all stylesheets in `document.stylesheets` doesn't work for some users. One users had a browser extension that adds stylesheets and trying to access them resulted in a cross origin policy exception. What I've come to do is to match on the href of the stylesheet and include matches of `boad.css` or `boards/tools/*.css`.

File: client-data/tools/download/download.js (hunk 3 above)
Comment (sents) [reply client-data/tools/download/download.js:36]: What browser versions should we target for compatibility when  writing PRs?

Comment (lovasoa) [reply client-data/tools/download/download.js:36]: wbo works on IE9.
It includes recent js polyfills for new es features: https://github.com/lovasoa/whitebophir/blob/master/server/server.js#L183-L199

But the es syntax itself has to be parsable by IE9

File: client-data/tools/download/download.js [hunk 4]
```diff
@@ -0,0 +1,64 @@
...
+            styleText += "\n" + Array.from(stylesheet.cssRules).map(x => x.cssText).join("\n");
+        });
```
[the remark this answers is not in the document]
Comment (DanielHabenicht) [reply client-data/tools/download/download.js]: done

File: client-data/tools/download/download.js (hunk 3 above)
Comment (DanielHabenicht) [reply client-data/tools/download/download.js]: done

**Comment by DanielHabenicht** [comment]
I've added your remarks and put in the stylesheet filtering mentioned by @sents

**Comment by DanielHabenicht** [comment]
Also added support for IE download, but I think that was the last time I handled something extra for IE (Just so you know: https://death-to-ie11.com/)

Some other tools also don't support IE: 

image

**Comment by DanielHabenicht** [comment]
> One more thing: Would you be interested in PNG Export as well (in another PR)?
> I would need to add a package for that https://github.com/canvg/canvg

@lovasoa are you open to that?

**Comment by sents** [comment]
> Some other tools also don't support IE:
> 
> image

Ah yes, that was my selector pull request. I'm working to make it IE compatible.

**Comment by lovasoa** [comment]
This looks great ! I'll try to merge later today !

**Comment by lovasoa** [comment]
It's merged and deployed. Thank you for this great contribution, @DanielHabenicht ! 🎉

**Comment by gigabyteservice** [comment]
@DanielHabenicht  if I will merge this [PR](https://github.com/lovasoa/whitebophir/pull/42) then this image download tool will create the problem ( download will works but if you will open that downloaded image then it will create the problem) , same thing is happening with this [PR](https://github.com/lovasoa/whitebophir/pull/124)  as well do you know how to solve this?

**Comment by DanielHabenicht** [comment]
Can you describe the problem? (In your Issue and CC me) 
I think the main problem ist the image embedding, not working seperatly (meaning only with SVG spec).
